# Generated by ./update.sh - do not update manually!
# Last updated: 2024-11-23
{
  version = "131.0.6778.86";
  url = "https://dl.google.com/chrome/mac/universal/stable/CHFA/googlechrome.dmg";
  hash = "sha256-d5UhIoi9uFjOYSNdaZ8z/tHp/piBk40IRbxWLtiziNE=";
}
