#! /usr/bin/env nix-shell
#! nix-shell -i bash --pure --keep GITHUB_TOKEN -p nix curl cacert _7zz xcbuild jq

set -euo pipefail

cd $(readlink -e $(dirname "${BASH_SOURCE[0]}"))

vendorDMG="googlechrome.dmg"
url="https://dl.google.com/chrome/mac/universal/stable/CHFA/${vendorDMG}" 

curl "${url}" -o "/tmp/${vendorDMG}"

hash=$(nix hash file "/tmp/${vendorDMG}")

7zz e "${vendorDMG}" -o/tmp/ "Google Chrome/Google Chrome.app/Contents/Info.plist"
version=$(plutil -extract CFBundleShortVersionString json -o - "/tmp/Info.plist" | jq -rc .)

cat > sources.nix << _EOF_
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{
  version = "${version}";
  url = "${url}";
  hash = "${hash}";
}
_EOF_
